FROM ruby:2.7
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN mkdir /doing
WORKDIR /doing
# COPY ./ /doing/
RUN gem install bundler:2.2.17
RUN apt-get update -y
RUN apt-get install -y less
CMD ["scripts/runtests.sh"]
